### ISSUE TITLE
Unresolved dependencies on compile droidel

### ISSUE THREAD

**Issue by adorilson** [cuplv/droidel#19]
I got the follow error when ran the "sbt compile"
[warn] 	Note: Unresolved dependencies path:
[warn] 		University of Colorado Boulder:walautil:0.1-SNAPSHOT (/home/adorilson/workspace/third_projects/droidel/build.sbt#L15-21)
[warn] 		  +- University of Colorado Boulder:droidel_2.10:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: University of Colorado Boulder#walautil;0.1-SNAPSHOT: not found

**Comment by sblackshear** [comment]
Hi Adorilson,
  Have you already run the `install_deps.sh` script in the `lib/` directory as the installation instructions suggest? Try that first if not. Otherwise, (though the script should have already have done this), try running `sbt publishLocal` in your `lib/walautil` directory. This will publish the walautil project to your local Maven repository and allow the dependency to be resolved.

**Comment by adorilson** [comment]
Txs, sblackshear.

It's works.
